/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class AddUser extends javax.swing.JFrame {

    String emailPattern = "^^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    String mobilePattern = "^[0-9]*$";
    public int checkUsername = 0;

    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
        iconName.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateDOB = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtmobileNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboUserRole = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        iconName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 16, 176, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 922, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 116, 37, -1));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 108, 265, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Date of Birth");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 188, -1, -1));
        getContentPane().add(dateDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 188, 265, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 281, 37, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 273, 265, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 82, 30));

        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 265, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 92, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 265, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Mobile Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 92, -1));
        getContentPane().add(txtmobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 265, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Role");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 345, 37, -1));

        comboUserRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Pharmacist", "Suported Staff", "Admin", " " }));
        getContentPane().add(comboUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 336, 247, 32));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 434, 105, 31));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 434, 94, 31));

        iconName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iconNameKeyReleased(evt);
            }
        });
        getContentPane().add(iconName, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all_pages_background.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iconNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_iconNameKeyReleased
    private Connection con;
    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        String username = txtUsername.getText();
        ResultSet resultSet = null;
        if (!username.equals("")) {
            iconName.setVisible(true);
            iconName.setIcon(new ImageIcon("src\\images\\yes.png"));
            iconName.setText("");
            checkUsername = 0;

            try {
                String url = "jdbc:mysql://localhost:3306/pharmacy";
                con = DriverManager.getConnection(url, "root", "lahiru@123");
                String checkQuery = "SELECT * FROM userlogin WHERE username = ?";
                PreparedStatement checkStmt = con.prepareStatement(checkQuery);
                checkStmt.setString(1, username);
                resultSet = checkStmt.executeQuery();

                while (resultSet.next()) {
                    checkUsername = 1;
                    iconName.setIcon(new ImageIcon("src\\images\\no.png"));
                    iconName.setText("");

                }
            } catch (SQLException e) {
                e.printStackTrace();

            }

        } else {
            iconName.setVisible(false);
        }


    }//GEN-LAST:event_txtUsernameKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String userRole = comboUserRole.getSelectedItem().toString();
        String name = txtname.getText();
        // SimpleDateFormat inputFormat = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = dateDOB.getDate();
        String dob = "";

        if (date != null) {
            dob = outputFormat.format(date);
        }
        String mobileNumber = txtmobileNumber.getText();
        String email = txtemail.getText();
        String password = new String(txtPassword.getPassword());
        String hashedPassword = hashPassword(password);
        String username = txtUsername.getText();
        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "Name Feild is Required");
        } else if (dob.equals("")) {
            JOptionPane.showMessageDialog(null, "DOB Feild is Required");
        } else if (mobileNumber.equals("")) {
            JOptionPane.showMessageDialog(null, "Mobile Number Feild is Required");
        } else if (!mobileNumber.matches(mobilePattern) || mobileNumber.length() != 10) {
            JOptionPane.showMessageDialog(null, "Mobile Number Feild is Invalid");
            txtmobileNumber.setText("");
            txtmobileNumber.requestFocus();

        } else if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "Email Feild is Required");
        } else if (!email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(null, "Email Feild is Invalid");
            txtemail.setText("");
            txtemail.requestFocus();
        } else if (username.equals("")) {
            JOptionPane.showMessageDialog(null, "Username Feild is Required");
        } else if (checkUsername == 1) {
            JOptionPane.showMessageDialog(null, "Username is Already Exsist");
        } else if (hashedPassword.equals("")) {
            JOptionPane.showMessageDialog(null, "Password Feild is Required");
        } else if (userRole.equals("None")) {
            JOptionPane.showMessageDialog(null, "Please Select the User Role");
        } else {
            PreparedStatement stmt = null;
//            PreparedStatement stmt1 = null;
            try {
                String url = "jdbc:mysql://localhost:3306/pharmacy";
                con = DriverManager.getConnection(url, "root", "lahiru@123");
                String insertQuery = "INSERT INTO useprofile (name, dob, email, username, password,role,mobilenumber) VALUES (?, ?, ?, ?, ?,?,?)";
            
                stmt = con.prepareStatement(insertQuery);
                stmt.setString(1, name);
                stmt.setString(2, dob);
                stmt.setString(3, email);
                stmt.setString(4, username);
                stmt.setString(5, hashedPassword);
                stmt.setString(6, userRole);
                stmt.setString(7, mobileNumber);
                stmt.executeUpdate();
                
                

//                String insertQuery1 = "INSERT INTO userlogin (name, email, password, role, username) VALUES (?, ?, ?, ?, ?)";
//                stmt1 = con.prepareStatement(insertQuery1);
//                
//                stmt1.setString(1, name);
//                stmt1.setString(2, email);
//                stmt1.setString(3, hashedPassword); 
//                stmt1.setString(4, userRole);
//                stmt1.setString(5, username);
//                stmt1.executeUpdate();
                
                
                

                JOptionPane.showMessageDialog(this, "Adding a User successful!");
                getClear();

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Adding User failed. Please try again.");
                getClear();
            } finally {
                try {

                    if (stmt != null) {
                        stmt.close();
                    }
                    if (con != null) {
                        con.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          new Login().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    private String hashPassword(String password) {
        try {
            // Create a MessageDigest instance for SHA-256
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            // Add the password bytes to the digest
            md.update(password.getBytes());

            // Get the hash's bytes
            byte[] bytes = md.digest();

            // Convert the bytes to a hexadecimal string
            StringBuilder sb = new StringBuilder();
            for (byte aByte : bytes) {
                sb.append(Integer.toString((aByte & 0xff) + 0x100, 16).substring(1));
            }

            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
            return null;
        }
    }

    public void getClear() {
        txtname.setText("");
        dateDOB.setDateFormatString("");
        txtemail.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtmobileNumber.setText("");
        comboUserRole.setSelectedItem("None");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboUserRole;
    private com.toedter.calendar.JDateChooser dateDOB;
    private javax.swing.JLabel iconName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmobileNumber;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
